# Generated by Django 3.0.14 on 2022-05-01 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_auto_20220430_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='region',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='usuario',
            field=models.CharField(max_length=20),
        ),
    ]
