# Generated by Django 3.0.14 on 2022-05-01 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20220501_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudadopcion',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
