# Generated by Django 3.0.14 on 2022-05-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20220502_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudadopcion',
            name='id_usuario',
        ),
    ]
